### ISSUE TITLE
cibuildwheels fails on python2.7 (travis) with OSError [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by benjaminweb** [joerick/cibuildwheel#10]
What's the reason letting it fail?

```
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.9/bin/cibuildwheel", line 9, in <module>
    load_entry_point('cibuildwheel==0.2.0', 'console_scripts', 'cibuildwheel')()
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/cibuildwheel/__main__.py", line 110, in main
    cibuildwheel.linux.build(**build_options)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/cibuildwheel/linux.py", line 104, in build
    stdin=subprocess.PIPE)
  File "/opt/python/2.7.9/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/opt/python/2.7.9/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

.travis.yml is

```
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
install: pip install -r requirements-appveyor.txt tox-travis
script:
  - tox
  - pip install urllib cibuildwheel==0.2.0
  - cibuildwheel --platform linux --output-dir wheelhouse
```

**Comment by sgeto** [comment]
was about to open an issue about that myself.
Were you able to get it to work?

**Comment by benjaminweb** [comment]
I dropped cibuildwheel and build the wheels on my own:

https://bitbucket.org/hyllos/effectus-python/src/8d5c9ff943cb73b72cabb6d149b3625be19d92d3/appveyor.yml?at=default&fileviewer=file-view-default#appveyor.yml-51,59,50

**Comment by sgeto** [comment]
That's sad to hear. I just discovered this and l love it!
In fact I actually got it to work. Turns out that docker does work on travis' precise machines (anymore).
Once you switch to trusty, It'll work like a charm.

Maybe this helps someone...

**Comment by joerick** [comment]
Thanks sgeto for working it out! Is that just a change to the travis yml? Let me know and I can update the readme

**Comment by benjaminweb** [comment]
Notice, I've not been able to get this working on appveyor.

**Comment by sgeto** [comment]
hey guys. sorry for the delay. I have a busy week. I'll reply soon

**Comment by joerick** [comment]
Hi guys, I just got back from a holiday so sorry for not being very useful before! I just re-tested our build on Travis and it's still working like before. I think the problem lies in your travis config. Cibuildwheel requires Docker so you'll need the `sudo: required` and `services: - docker` lines in your config. https://docs.travis-ci.com/user/docker/

Check the [Minimal config](https://github.com/joerick/cibuildwheel#minimal-setup) section of the readme for known working Travis configs.

By the way, you don't need to specify the `language: python` and python versions in `.travis.yml` - the python versions matrix is specified inside cibuildwheel itself, and can be controlled with `CIBW_SKIP`.

@benjaminweb, have you got a link to the appveyor build and your config so I can take a look at that too?

**Comment by benjaminweb** [comment]
@joerick welcoming you back from your holiday.

I remember but cannot locate the build I stumbled over the issue.

Anyway, my configs as follows:

https://bitbucket.org/hyllos/effectus-python/src/default/.travis.yml
https://bitbucket.org/hyllos/effectus-python/src/default/appveyor.yml

The CI builds:
https://travis-ci.org/benjaminweb/effectus-python
https://ci.appveyor.com/project/hyllos/effectus-python

Which advantage would I have opting for cibuildwheel considering my current setup?

**Comment by joerick** [comment]
Thanks @benjaminweb! 

It looks like you'e building pure Python wheels. In that case, there's really no big advantage in using cibuildwheel - it's really designed for building 'platform' wheels where there is a compiled C component that tightly couples it to the Python version and operating system - that's when you need the extra tooling around OSs. `python setup.py bdist_wheel` should be just fine for you.

**Comment by benjaminweb** [comment]
Well, I do have C bindings in my package (base case is to compile shipped .c file).
I deem a wheel important as it releases the end-user from the need of installing dev-tools, for windows ~4.5 GiB of Visual Studio stuff.

**Comment by joerick** [comment]
Ah, I found a pure wheel [on PyPI](https://pypi.org/project/effectus/#files) so assumed that's what you intended. Your project is building as a pure wheel due to the presence of `universal = 1` in your setup.cfg. However if you intend to ship compiled wheels you'll need to remove that as pip will prefer to install a universal wheel over a platform wheel.

So, using cibuildwheel instead of your current setup might provide you with help setting up all the different environments for Mac/Win/Linux. But if you're happy with your current setup then more power to you!
