### ISSUE TITLE
Provide a way to pass custom flags to pip wheel

### ISSUE THREAD

**Issue by astrofrog** [joerick/cibuildwheel#120]
I maintain some packages (e.g. fast-histogram) for which I make use of ``pyproject.toml`` to define build-time dependencies (as per the new PEP 518):

```
[build-system]
requires = ["setuptools", "wheel", "numpy"]
```

Now cibuildwheel does the following:

```
pip install numpy==1.12.1
pip wheel fast-histogram
```

The issue is that pip wheel by default will actually re-install numpy because it's defined in ``pyproject.toml`` and will actually compile the package over a more recent version of numpy. I'm not sure of the motivation for this behavior, but the solution is to run ``pip wheel`` with the ``--no-build-isolation`` option.

So I think either ``--no-build-isolation`` should be added by default to the ``pip wheel`` commands here, or if you don't agree, it would be nice to at least have a way for users to add flags to ``pip wheel`` (the first is in my opinion the better option because, in the same way that you use ``--no-deps`` to ignore install_requires, you basically want to force pip to really not install any dependencies if a ``pyproject.toml`` file is present)

**Comment by joerick** [comment]
Hmm, interesting. As I understand it, the build isolation features in pip are designed to encourage reproducible builds among python packages i.e. remove dependency on stuff that just happens to be there at build time. So the isolation means that only the stuff declared is available during the build. Now in your case, the BEFORE_BUILD installed numpy isn't available to the build because of this. (Just thinking aloud, correct me if I'm wrong!). An option to add flags could be possible, but I have a couple questions

- Why do you need the 'install numpy' step in BEFORE_BUILD ?
- What's the problem with installing it in both places? Build time, or something more?

Thanks

**Comment by joerick** [comment]
@astrofrog did you try specifying the numpy version you want in the `build-system` section of pyproject.toml? I'm thinking something like this should work--

```
[build-system]
requires = ["setuptools", "wheel", "numpy==1.12.1"]
```

(That said, the use of build isolation in pip looks like it's reducing BEFORE_BUILD's usefulness. Since that's the way things are going (after PEP 518), I don't want to blanket disable build isolation if I can help it. Though I can see an option being useful in the transition period. interesting reading at https://github.com/scipy/scipy/issues/8734)

**Comment by astrofrog** [comment]
@joerick - ah interesting, I'll take a look at the scipy and pip discussions.

**Comment by astrofrog** [comment]
Now that I understand PEP517/PEP518 better, I'm going to close this since the build isolation is indeed desirable!
