### ISSUE TITLE
linux wheel docker fail without propagation

### ISSUE THREAD

**Issue by Czaki** [joerick/cibuildwheel#205]
When docker build fail it is not propagated and `cibuildwheel` finish with success:

Here is log:
https://dev.azure.com/PartSeg/PartSeg/_build/results?buildId=399&view=logs&j=f985d524-9506-5613-fc85-37284f210317&t=41b4c4a7-ed40-5c6d-2a05-217ce80d9e2e&l=910

**Comment by YannickJadoul** [comment]
Which docker? The link doesn't work?
Do you mean Linux builds in the `manylinux` docker images?

**Comment by Czaki** [comment]
Yes. Line 910. I do not expect that this link fail.

**Comment by YannickJadoul** [comment]
Is this new? Did it work before?

**Comment by Czaki** [comment]
Reason why build fail is new. I try add build wheel for python 3.8. But I expect that in such case i got information about error in build pipeline.

**Comment by YannickJadoul** [comment]
Isn't this because of your Azure configuration?
I found this, in the commit: https://github.com/4DNucleome/PartSeg/commit/b790470e6017df150ced3f164081ac35caca8936#diff-fec826feae04e51c0d94076385408bdcR118-R121 That's the correct part of the YAML file, right?

So, I think `cibuildwheel` correctly exits with a non-zero exit code (please check), but because you have a multiline bash script without `set -e` (or `set -o errexit`), bash just continues.

Do feel free to check the error code of `cibuildwheel` by adding a `echo $?` statement after `cibuildwheel`, but I'm fairly optimistic that this isn't a `cibuildwheel` problem.

**Comment by Czaki** [comment]
I do not expect that azure bash work in this mode. Thanks

**Comment by YannickJadoul** [comment]
> I do not expect that azure bash work in this mode

I'm not sure either, though. But it's my best guess. You might want to just try?

**Comment by Czaki** [comment]
I already try before closing issue 
https://dev.azure.com/PartSeg/PartSeg/_build/results?buildId=401&view=logs&s=7c21511b-3ca2-5fdd-b984-fc3a67796474&j=f985d524-9506-5613-fc85-37284f210317

**Comment by YannickJadoul** [comment]
Oh, OK. Thanks, good to know!

**Comment by takluyver** [comment]
I just made this mistake as well. Would it make sense to add `set -e` to the [Azure pipelines example](https://cibuildwheel.readthedocs.io/en/stable/setup/#azure-pipelines) in the docs? It's not so bad where cibuildwheel is the last command, but it's easy to stick another command after it and forget how bash behaves.

**Comment by henryiii** [comment]
This was considered a mistake by Azure, and they fixed it with GitHub Actions, but said it was not possible to fix Azure, the ship had sailed on changing such a big default.

**Comment by henryiii** [comment]
Steps really should be one per "action", so adding the set -e directly to the example seems to possibly be promoting bad behavior. Maybe a comment warning about the need to have `set -e` for multiline steps at the top?

**Comment by joerick** [comment]
> This was considered a mistake by Azure, and they fixed it with GitHub Actions, but said it was not possible to fix Azure, the ship had sailed on changing such a big default.

microsoft really take that backward compat thing seriously huh!

> Steps really should be one per "action", so adding the set -e directly to the example seems to possibly be promoting bad behavior. Maybe a comment warning about the need to have set -e for multiline steps at the top?

Our example config uses a bash multiline script, so I think we should be adding `set -o errexit`, because this is kinda a nasty surprise for unsuspecting users e.g. "my build was successful, I can cut a release. oh wait actually everything is on fire!"

**Comment by henryiii** [comment]
This is as close to resolved as possible, I think, with #461.
