### ISSUE TITLE
A few questions related to appveyor

### ISSUE THREAD

**Issue by lelit** [joerick/cibuildwheel#22]
Trying to get binary wheels built, tested and deployed from ci.appveyor.com, most of the things are going smoothly, except:

1. In the [appveyor log](https://ci.appveyor.com/project/lelit/python-rapidjson/build/1.0.25) there are [several](https://ci.appveyor.com/project/lelit/python-rapidjson/build/1.0.25#L20) `fatal: BUG: setup_git_env called without repository` messages in row, each taking as long as a whole minute to appear, just after cibuildwheel starts: is this something related to the tool, some bad setting on my side, or simply something I should not care about? 
2. Even if the `CIBW_TEST_COMMAND` [appears in log](https://ci.appveyor.com/project/lelit/python-rapidjson/build/1.0.25#L67) (see [here](https://github.com/python-rapidjson/python-rapidjson/blob/master/appveyor.yml) for the configuration), the command does not seem to be executed (on GNU/Linux the test suite takes several tens of seconds, I cannot believe that Windows can be so much faster 😈), nor it does produce some output
3. The final `twine upload` exits with an [error](https://ci.appveyor.com/project/lelit/python-rapidjson/build/1.0.25#L129), even though it actually [uploaded](https://pypi.python.org/pypi/python-rapidjson/0.1.0b3) the win32 and win_amd64  wheels

Do you have any hint on how I could solve any of above?

Thank you in advance!

**Comment by joerick** [comment]
Hey there @lelit!

> 1. `fatal: BUG: setup_git_env called without repository`

Git isn't used directly by cibuildwheel, so this must be coming from an invocation of git by `pip`, perhaps. It seems to be something that's [occurred in a recent version](https://www.spinics.net/lists/git/msg305185.html) of Git, and if I'm reading that thread right it's actually pretty harmless.

> 2 `CIBW_TEST_COMMAND` does not seem to be executed

That's strange, not something I've seen before. The config looks okay to me, perhaps add some verbosity to that command to see if you can see what's going on.

> 3 twine upload exits with an error

Windows thinks any output on stderr means the command failed, so that's why it looks bad. Actually the command succeeded so there's no need to worry :). Might be worth logging that as a bug on the twine repo (switching the log messages to stdout on Windows).

**Comment by lelit** [comment]
Ok, thank you!

**Comment by lelit** [comment]
About the second point, the _verbosity_ was already set to “detailed” in the appveyor's project settings, but that didn't make any difference wrt to what is logged in the console. For example, neither the output of [python --version](https://ci.appveyor.com/project/lelit/python-rapidjson/build/1.0.25#L52) appears in the log.

Anyway, I realize this is most probably not related to cibuildwheel, so I will try to understand the issues without boring you :-)
