### ISSUE TITLE
How strong tests should protect developer against himself 

### ISSUE THREAD

**Issue by Czaki** [joerick/cibuildwheel#224]
Just after PR #221 was merged I realized that there is scenario that some developer, which make stupid changes in `cibuildwheel.__main__.py` it is possible that unit test can call `build` for some platform and  make changes on developer machine. 

Such person can be protected by add some monkeypatch which replace all `build` function with empty call. 
But it will increase code to be maintained. 

What you think about this?

@mayeut

**Comment by YannickJadoul** [comment]
> Just after PR #221 was merged I realized that there is scenario that some developer, which make stupid changes in `cibuildwheel.__main__.py` it is possible that unit test can call `build` for some platform and make changes on developer machine.

If I understand correctly, this is probably a rather rare case, or not? Only very rarely do we actually interact with platform detection, right?

> Such person can be protected by add some monkeypatch which replace all build function with empty call.
But it will increase code to be maintained.

Do you have any estimate on the amount of code this would be? Would it just be a few lines in `conftest.py` (that seems reasonable), or a whole amount extra in `__main__.py` (less enthusiast about that).

> What you think about this?

Alternatively: what about making sure the integration tests do not run by default, but only when you pass an extra argument to `pytest` or so? As a result, 1) we'd maybe write more unit tests rather than full integration tests, which is good, and 2) that makes it explicit to the developer when starting the tests that he should be careful (and should make him realize if he has been working on `__main__.py`), as you cannot run these tests "by accident".

This is all only relevant if/when we replace `run_tests.py` by a `pytest` invocation, right? (@joerick didn't seem very happy about that, before.)

**Comment by Czaki** [comment]
> If I understand correctly, this is probably a rather rare case, or not? Only very rarely do we actually interact with platform detection, right?

This is rare (I have hope really rare) case and tests will detect this. But before test fail it will introduce changes in running system  

> Do you have any estimate on the amount of code this would be? Would it just be a few lines in conftest.py (that seems reasonable), or a whole amount extra in __main__.py (less enthusiast about that).

My way to solve this will only increase amounts of lines in tests. For safety purpose it will mock `macos.build`, `linux.build`, `windows.build`, `subprocess.check_call` and maybe few others functions which calls can create some system changes. 

Following suggestion of @mayeut tests introduced in #221 are unit test, not integration tests. And same problem may show with other unit tests. If they are tests `main()` function then there is possible that someone modify code and this test will fire building process. 

Whole problem is not connected with making tests pytest callable.

**Comment by YannickJadoul** [comment]
> Whole problem is not connected with making tests pytest callable.

Well, it is, right? If you call `./run_tests.py` this is explicit and you are aware you are calling the integration tests. If you would call just `pytest` and integration tests start, that's a bit unexpected perhaps.

(By the way, I most of the time just test the integration tests through the CI building in the PRs anyway; of course this results in a lot of force-pushes, but since `cibuildwheel` is by definition cross-platform, this just seems easier.)

**Comment by YannickJadoul** [comment]
> If they are tests main() function then there is possible that someone modify code and this test will fire building process.

Only integration tests should call `main`, btw. A unit test calling `main` is weird, no?

**Comment by Czaki** [comment]
Suggestion tu put it in unit test is from this comment https://github.com/joerick/cibuildwheel/pull/214#discussion_r347131073
If I good understand Idea for putting this test here is that it is critical to be sure that if platform is not set then no calculation is executed.

**Comment by YannickJadoul** [comment]
Maybe that unit test could do with a few more `monkeypatch`es, yes?
