### ISSUE TITLE
Building wheels for  Py 2.7, 3.5, 3.6, 3.7 with C++11 compiler

### ISSUE THREAD

**Issue by jtrmal** [joerick/cibuildwheel#251]
Hi, I have created setup that builds wheels for this project: https://github.com/sequitur-g2p/sequitur-g2p.
The issue is that the project uses heavily C++11, so my understanding is that I cannot build the wheels for the aforementioned packages (or at least it failed because of non-existing headers introduced in C++11). Is there a way around it? Thanks for your time -- I tried to go through docs and PRs and it seems it should be possible in the future but not at this time.  Is that right or is there a possibility how to do it?

**Comment by YannickJadoul** [comment]
@jtrmal There's a long-standing PR that should soon get merged and includes some docs on what's possible here: https://github.com/joerick/cibuildwheel/pull/156/files#diff-696b5e631bcfe233e0e5247a751eb20f

In general, it is quite possible to do so; I'm building wheels with C++17 using cibuildwheel in my [Parselmouth](https://github.com/YannickJadoul/Parselmouth) projects. There are a few caveats:
- For manylinux wheels, you need to statically link libstdc++, though from manylinux2010 onwards, C++11 is supported already (see https://github.com/pypa/manylinux/issues/118)
- On macOS, currenlty, the wrong tag gets added to the built wheels (indicating compatibility with a lower macOS version than it actually is; that's what's being solved by #156). In practice, this is not a problem since most macOS versions are modern enough.
- On Windows, you need to build with VS2017 or VS2019; and this means that users will need to have a newer Visual C++ redistributable installed for older Python versions (though I think from 3.6 or 3.7, the C++ standard library that's delivered along with the Python installation is modern enough; see https://parselmouth.readthedocs.io/en/stable/installation.html#importerror-dll-load-failed-on-windows, https://wiki.python.org/moin/WindowsCompilers, and https://pybind11.readthedocs.io/en/stable/faq.html#working-with-ancient-visual-studio-2008-builds-on-windows)

**Comment by jtrmal** [comment]
Thanks for the quick response, I will check out your stuff in the project.
Y.

**Comment by YannickJadoul** [comment]
Don't take it as the only way to do things, though; there might still be problems. I've just done my best to get something working, and haven't had too many complaints of things not working in practice, yet.

**Comment by jtrmal** [comment]
I understand, that makes a complete sense.
Thanks.

**Comment by jtrmal** [comment]
I'm marking it as resolved, as I was able to succeed. Thanks for the assistance!
