### ISSUE TITLE
Example that builds. so and includes it?

### ISSUE THREAD

**Issue by stuaxo** [joerick/cibuildwheel#253]
Hi,
   cibuildwheel looks really good :)

I'm looking at porting a script that has downloads and compiles some libraries

https://gist.github.com/anntzer/a03230f94e6d111ba3abc737d5091b99

Is there a cibuildwheel example where a .so is compiled as part of the process ?

**Comment by YannickJadoul** [comment]
@stuaxo What exactly do you mean? The Python extensions are also `.so` shared libraries, but you are referring to external dependencies of your wheel?

I don't think we have an example, but you can just pre-build the dependencies before calling `cibuildwheel`. If you need to build the dependencies for each Python version (because they use the CPython API or so), you can use `CIBW_BEFORE_BUILD`. To set environment variables needed for building your wheel, you can use `CIBW_ENVIRONMENT`.

So, if I very briefly look at the gist you posted, `cibuildwheel` will take care of everything that has to do with building the wheel: i.e., `PYTHON_VERSION=...`, `PIP`, `docker`, `build_wheel`, and `auditwheel`. The rest is specific to your use case, and I'd say you should run those parts before running `cibuildwheel` or in `CIBW_BEFORE_BUILD`. Does that help?

**Comment by stuaxo** [comment]
I think so ..  I will have a play, at the moment my understanding of the process is a bit fuzzy.

Does cibuildwheel use a docker container to build the wheels, and if I am building some libraries, such as cairo etc, then they will be accessible by all the tools that build the wheel so they get included propperly?

I'll close this for now, as it's not a real bug, but come back when I've had a some time to give this a go.

**Comment by YannickJadoul** [comment]
> [...] but come back when I've had a some time to give this a go.

Yes, please do! Just let me know if you need more input/feedback :-)
