### ISSUE TITLE
Travis CI with suggested .travis.yml cannot find "twine"

### ISSUE THREAD

**Issue by brandon-rhodes** [joerick/cibuildwheel#266]
Thanks for writing cibuildwheel! It was the key to starting back up my old habit of releasing C-accelerated Python libraries, by letting me support platforms I don't have locally.

I was especially happy to see the recent support for 3-platform builds using only Travis CI. The feature worked great the first time I used it, but earlier this week ran into a snag —

https://travis-ci.org/brandon-rhodes/python-sgp4/jobs/646174937

```
/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: No module named twine
```

My `.travis.yml` is essentially the example one shown in your docs, except I trigger upload under slightly different conditions:

https://github.com/brandon-rhodes/python-sgp4/blob/632b3e60d7a4f6ba5662830811c4bf614cfba741/.travis.yml#L1

Do you have any insight as to why `twine` cannot be found by `python -m` under osx? If not then I can begin iterating with `which` and `find` and `echo` and so forth, but I thought that I would start by asking if there were anything obviously wrong with how I pasted and used the example YAML. Thanks!

**Comment by joerick** [comment]
Hey! Thanks for the kind words, and for bringing this up.

I have seen this before. As a result of cibuildwheel installing other versions of Python as part of its operation, the `python` you use at the start of the script, and the `python` at the end are different, and have different environments.

I'd recommend trying a `python -m pip install twine` in your `after_success` block, rather than doing it at the start of the script.

Let us know if that fixes it - we should look at updating the examples if that's so.

**Comment by brandon-rhodes** [comment]
It worked! I changed the last line of the script to:

```
  - if [[ -n "$TWINE_PASSWORD" ]]; then python -m pip install twine; python -m twine upload wheelhouse/*.whl; fi
```

Thanks for getting me back into business. I'll leave the issue open for you to close once you've done any doc updates.

**Comment by brandon-rhodes** [comment]
Looks great, thanks for the update!
