### ISSUE TITLE
Docs updates

### ISSUE THREAD

**Issue by henryiii** [joerick/cibuildwheel#301]
I have started testing this after the addition of GHA and am quite excited to see it seems to cover most of the "special" things I had to do for boost-histogram, and almost everything else I've had to do for other packages. I just have a few documentation bug reports/requests:

* The [environment docs](https://cibuildwheel.readthedocs.io/en/stable/options/#setting-options) do not show examples for GHA (I can help add those)
* The [docs claim](https://cibuildwheel.readthedocs.io/en/stable/cpp_standards/#macos-and-deployment-target-versions)  that MACOS_DEPLOYMENT_TARGET is set to 10.9 by default, but it does not seem to be set at all. It is quite important to set at least 10.9, but in order to make it easy to change, maybe it's best not set by default, but the docs should be corrected.
* The docs mention the [PyBind Win + 2.7 workaround](https://cibuildwheel.readthedocs.io/en/stable/cpp_standards/#windows-and-python-27), but don't show how to do that in cibuildwheel.

**Comment by joerick** [comment]
> * The [docs claim](https://cibuildwheel.readthedocs.io/en/stable/cpp_standards/#macos-and-deployment-target-versions)  that MACOS_DEPLOYMENT_TARGET is set to 10.9 by default, but it does not seem to be set at all. It is quite important to set at least 10.9, but in order to make it easy to change, maybe it's best not set by default, but the docs should be corrected.

Yeah... we currently don't set `MACOS_DEPLOYMENT_TARGET`, we just use a version of Python that guarantees the resulting wheel will be 10.9+. I had thought that setuptools was setting this, but I guess I'm wrong. I'd propose setting `MACOS_DEPLOYMENT_TARGET=10.9`, if the user hasn't set it. What do you think, @Czaki?

> * The docs mention the [PyBind Win + 2.7 workaround](https://cibuildwheel.readthedocs.io/en/stable/cpp_standards/#windows-and-python-27), but don't show how to do that in cibuildwheel.

To be completely honest, I don't know. @YannickJadoul might be more help here.

**Comment by henryiii** [comment]
> we just use a version of Python that guarantees the resulting wheel will be 10.9+

10.7, actually, which is why I noticed the docs were not correct. To support macOS 10.14/10.15, I think you have to set 10.9 or higher.

**Comment by YannickJadoul** [comment]
Hey, @henryiii! Thanks for the sharp eye and remarks!

>     * The [docs claim](https://cibuildwheel.readthedocs.io/en/stable/cpp_standards/#macos-and-deployment-target-versions)  that MACOS_DEPLOYMENT_TARGET is set to 10.9 by default, but it does not seem to be set at all. It is quite important to set at least 10.9, but in order to make it easy to change, maybe it's best not set by default, but the docs should be corrected.

> 10.7, actually, which is why I noticed the docs were not correct (at least for some variants). To support macOS 10.14/10.15, I think you have to set 10.9 or higher. (C++ only)

We've recently (release 1.0? Or 1.1?) switched to using the 64-bit-only macOS Python.org packages. So if I recall correctly (@Czaki did all the heroic research and implementation here), the minimum version used by setuptools/wheel (I forgot which one enforces this) is 10.9 (since that's the target version the Python distribution was build for), even if no `MACOS_DEPLOYMENT_TARGET` is set.

>     * The docs mention the [PyBind Win + 2.7 workaround](https://cibuildwheel.readthedocs.io/en/stable/cpp_standards/#windows-and-python-27), but don't show how to do that in cibuildwheel.

There are links to https://pybind11.readthedocs.io/en/stable/faq.html#working-with-ancient-visual-studio-2008-builds-on-windows and https://github.com/pybind/python_example? But yeah, if you're busy updating the docs, I see no harm in copying the instructions from `pybind/python_example`'s README, so that users don't have to look for themselves?

**Comment by YannickJadoul** [comment]
> 10.7, actually, which is why I noticed the docs were not correct (at least for some variants). To support macOS 10.14/10.15, I think you have to set 10.9 or higher. (C++ only)

I'm not entirely getting this, btw. To support 10.14/10.15, there's also a minimum `MACOS_DEPLOYMENT_TARGET` that should have been set?
Apple's documentation around this all is so crappy (or at the very least hard to find), so if this is the case, anything we can include in our docs for our users is really helpful, I'd say!

**Comment by henryiii** [comment]
Check [the logs](https://pipelines.actions.githubusercontent.com/hpT3mfzPgddTbiihkpZnNK38IoMlbrL0ewaK7Ji3mq7IAHaRX1/_apis/pipelines/1/runs/272/signedlogcontent/3?urlExpires=2020-03-31T20%3A08%3A59.9514266Z&urlSigningMethod=HMACV1&urlSignature=bamNyrJtMR6g%2BTnE3iLm%2FJ3ckKKCRk1zT1fM8VRdN1g%3D) if you'd like, you'll see that many of the images build with 10.7, and it's even complaining that MACOS_DEPLOYMENT_TARGET is 10.3. I think that is true - the minimum comes from the python you are using - however, the 2.7 and 3.5 versions are still fat binaries and are 10.6 (so not sure where 10.7 comes from).

If you build against C++, you need 10.9 or better to link to libc++ instead of libstdc++, which was deprecated in 10.9 and removed in 10.14. So I *believe*, for a C++ lib, you need 10.9+ or better to work on 10.14/10.15, since that changes that default.

**Comment by henryiii** [comment]
> I see no harm in copying the instructions from

I'd like to see it as applied to cibuildwheel; I'm not quite sure how to set this for just Python 2.7 Windows.

**Comment by Czaki** [comment]
@henryiii 

> The docs mention the PyBind Win + 2.7 workaround, but don't show how to do that in cibuildwheel.

If anyone have time to investigate this we could remove installing of  `vcpython27` before test and add support of python 2.7 on travis. It is added to documentation to give user starting point of his investigation. 

But `vcpython2.7` is installable on azure, github, etc. Maybe on travis also but windows image is still in early stage so it may be unstable. 

For github you can see here working configuration (from cibuildwheel tests) https://github.com/joerick/cibuildwheel/blob/master/.github/workflows/test.yml. See this:
```yaml
    - name: Install Visual C++ for Python 2.7
      if: startsWith(matrix.os, 'windows')
      run: |
        choco install vcpython27 -f -y
```


Log link expired. So I cannot check it. Current release of cibuildwheel use 10.9 x86_64 python binaries. Is there any reason that you would like to build fat libraries?  

From my experience If you set `MACOS_DEPLOYMENT_TARGET` lower than python is compiled then build will fail with proper message. 

> 10.7, actually, which is why I noticed the docs were not correct (at least for some variants). To support macOS 10.14/10.15, I think you have to set 10.9 or higher. (C++ only)

Unpack build wheel and check produced binaries file (extension .so) with `otool -L`. You will see that minimum 10.9 (if you do not set MACOS_DEPLOYMENT_TARGET).

**Comment by henryiii** [comment]
Try this link: https://github.com/scikit-hep/boost-histogram/runs/549332108?check_suite_focus=true 

I think vcpython2.7 and the PyBind11 workaround are separate - there might be times when you are able to build your code with Visual Studio 2008 - just as long as you avoid C++11 or newer, and it does add a dependency on the redistributable (minor). PyBind11 extensions obviously can't do that.

No, I don't ever want anything less than 10.9. I don't like it warning and spitting out files with a 10.7 in them though, but I haven't verified to see if they work locally - if the cibuildwheel testing is working though, they should be fine.

**Comment by henryiii** [comment]
"Fine" meaning they work on 10.14 or 10.15, not "fine" meaning they work where they look like they could work (10.7 or 10.8).

**Comment by Czaki** [comment]
> Try this link: https://github.com/scikit-hep/boost-histogram/runs/549332108?check_suite_focus=true

Oh. I forget. `pypy` is build against macos 10.7. cpython is build against 10.9. 

> I think vcpython2.7 and the PyBind11 workaround are separate - there might be times when you are able to build your code with Visual Studio 2008 - just as long as you avoid C++11 or newer, and it does add a dependency on the redistributable (minor). PyBind11 extensions obviously can't do that.

Yes. Of course. Maybe it be more clarified in docs. @joerick @YannickJadoul What do you think? 

>"Fine" meaning they work on 10.14 or 10.15, not "fine" meaning they work where they look like they could work (10.7 or 10.8).

Github macos images are 10.15. Azure pipelines minimal macos image is 10.14. So if test of package pass then it should work.

**Comment by YannickJadoul** [comment]
> Check [the logs](https://pipelines.actions.githubusercontent.com/hpT3mfzPgddTbiihkpZnNK38IoMlbrL0ewaK7Ji3mq7IAHaRX1/_apis/pipelines/1/runs/272/signedlogcontent/3?urlExpires=2020-03-31T20%3A08%3A59.9514266Z&urlSigningMethod=HMACV1&urlSignature=bamNyrJtMR6g%2BTnE3iLm%2FJ3ckKKCRk1zT1fM8VRdN1g%3D) if you'd like, you'll see that many of the images build with 10.7, and it's even complaining that MACOS_DEPLOYMENT_TARGET is 10.3. I think that is true - the minimum comes from the python you are using - however, the 2.7 and 3.5 versions may still be the old fat binaries and are 10.6 (so not sure where 10.7 comes from). I know I was only able to find the 64 bit only versions for 3.6 and on (and maybe 2.7?).

> > Try this link: https://github.com/scikit-hep/boost-histogram/runs/549332108?check_suite_focus=true
> 
> Oh. I forget. `pypy` is build against macos 10.7. cpython is build against 10.9.

So, does this mean it does work? I think we've documented PyPy's alternative versions somewhere, no? But where does the warning then come from, @Czaki? We should still get rid of it, if possible, and avoid further confusion.

By the way, [for CPython 2.7 we are using a 10.9 64-bit package](https://github.com/joerick/cibuildwheel/blob/40ff745321112ff802f1aa4dffa06634f365f901/cibuildwheel/macos.py#L30), and (for 3.5, there's a line setting `MACOS_DEPLOYMENT_TARGET`](https://github.com/joerick/cibuildwheel/blob/40ff745321112ff802f1aa4dffa06634f365f901/cibuildwheel/macos.py#L166-L174).

> If you build against C++, you need 10.9 or better to link to libc++ instead of libstdc++, which was deprecated in 10.9 and removed in 10.14. So I _believe_, for a C++ lib, you need 10.9+ or better to work on 10.14/10.15, since that changes that default.

Right, thanks. That makes sense, yes. Worth adding to the docs! (Does this also imply that from 10.14, you cannot target 10.6 anymore?)

> > I see no harm in copying the instructions from
> 
> I'd like to see it as applied to cibuildwheel; I'm not quite sure how to set this for just Python 2.7 Windows. Basically what I do here for my pre-cibuildwheel script collection:
> 
> https://github.com/scikit-hep/azure-wheel-helpers/blob/584654468abd604f46c64a02c3547cb0179ffee2/azure-steps.yml#L8-L14

Hmmm, I'm not fully convinced by this, since doing it does come with a caveat, I've noticed: you need to have the right Visual C++ runtime installed. While the one that Python is build against is part of the Python distribution (VC++ 9.0 for Python 2.7, see [here](https://wiki.python.org/moin/WindowsCompilers)), if you build with a different compiler, you might need to separately install the newer VC++ runtime. I've tried this out for my library, and added [some instructions to my docs](https://parselmouth.readthedocs.io/en/latest/installation.html#importerror-dll-load-failed-on-windows) to make sure I can distribute a C++11 (C++17 by now) Python extension to Windows.

So, yes, this whole explanation should actually be in the docs (added to my TODO list, thanks!). But I'm not convinced this should be a cibuildwheel default. We could think about having this as a switch, though, perhaps? Then again, Python 2.7 is almost dead, so ... not sure it's worth it. If you still want to support 2.7 in a year, this won't be the biggest hurdle, I suspect. @joerick, any thougths.

> If anyone have time to investigate this we could remove installing of `vcpython27` before test and add support of python 2.7 on travis. It is added to documentation to give user starting point of his investigation.

So, @Czaki, I know what to do, but I'm not sure we should always replace vcpython2.7? Maybe we can make the "modern C++" tests succeed for 2.7, though?

> "Fine" meaning they work on 10.14 or 10.15, not "fine" meaning they work where they look like they could work (10.7 or 10.8).

Is this mutually exclusive? Can we tests whether a wheel that says 10.7 doesn't only work on 10.14/10.15, but also on 10.7; can we get access to a OS X 10.7 (virtual) machine?

**Comment by Czaki** [comment]
> > Check [the logs](https://pipelines.actions.githubusercontent.com/hpT3mfzPgddTbiihkpZnNK38IoMlbrL0ewaK7Ji3mq7IAHaRX1/_apis/pipelines/1/runs/272/signedlogcontent/3?urlExpires=2020-03-31T20%3A08%3A59.9514266Z&urlSigningMethod=HMACV1&urlSignature=bamNyrJtMR6g%2BTnE3iLm%2FJ3ckKKCRk1zT1fM8VRdN1g%3D) if you'd like, you'll see that many of the images build with 10.7, and it's even complaining that MACOS_DEPLOYMENT_TARGET is 10.3. I think that is true - the minimum comes from the python you are using - however, the 2.7 and 3.5 versions may still be the old fat binaries and are 10.6 (so not sure where 10.7 comes from). I know I was only able to find the 64 bit only versions for 3.6 and on (and maybe 2.7?).
> 
> > > Try this link: https://github.com/scikit-hep/boost-histogram/runs/549332108?check_suite_focus=true
> > 
> > 
> > Oh. I forget. `pypy` is build against macos 10.7. cpython is build against 10.9.
> 
> So, does this mean it does work? I think we've documented PyPy's alternative versions somewhere, no? But where does the warning then come from, @Czaki? We should still get rid of it, if possible, and avoid further confusion.

I do not have any idea. Maybe some enviroment variable seted in github actions? But cibuildwheel test passes. 

> By the way, [for CPython 2.7 we are using a 10.9 64-bit package](https://github.com/joerick/cibuildwheel/blob/40ff745321112ff802f1aa4dffa06634f365f901/cibuildwheel/macos.py#L30), and for 3.5, there are [lines setting `MACOS_DEPLOYMENT_TARGET`](https://github.com/joerick/cibuildwheel/blob/40ff745321112ff802f1aa4dffa06634f365f901/cibuildwheel/macos.py#L166-L174).
> 
> > If you build against C++, you need 10.9 or better to link to libc++ instead of libstdc++, which was deprecated in 10.9 and removed in 10.14. So I _believe_, for a C++ lib, you need 10.9+ or better to work on 10.14/10.15, since that changes that default.
> 
> Right, thanks. That makes sense, yes. Worth adding to the docs! (Does this also imply that from 10.14, you cannot target 10.6 anymore?)
 
Are you sure? I do fast gogling and they report problem with compiling against libstdc++ not using software compiled against libstdc++. For me it looks like they remove header files, not binaries blob. Do you @henryiii  have some documentation about this?

> > If anyone have time to investigate this we could remove installing of `vcpython27` before test and add support of python 2.7 on travis. It is added to documentation to give user starting point of his investigation.
> 
> So, @Czaki, I know what to do, but I'm not sure we should always replace vcpython2.7? Maybe we can make the "modern C++" tests succeed for 2.7, though?

Yes. But it need time to understand windows compilers And question is if it is worth if there is plan to drop  python 2.7 (and pypy 2.7 ?) support. But Maybe you will have more luck 

> 
> > "Fine" meaning they work on 10.14 or 10.15, not "fine" meaning they work where they look like they could work (10.7 or 10.8).
> 
> Is this mutually exclusive? Can we tests whether a wheel that says 10.7 doesn't only work on 10.14/10.15, but also on 10.7; can we get access to a OS X 10.7 (virtual) machine?

I still think that is is still drop of compiling support, not execution.

**Comment by YannickJadoul** [comment]
>  But cibuildwheel test passes.

We don't test for warnings, though, and they are hidden if not run with the verbose flag and when the test succeeds.

> Yes. But it need time to understand windows compilers And question is if it is worth if there is plan to drop python 2.7 (and pypy 2.7 ?) support. But Maybe you will have more luck

If decisions are made what to do, I will try. If it turns out to be too hard, we can still quit.

**Comment by joerick** [comment]
This thread is getting confusing, there are too many things being discussed at once. I've created #306 re setting MACOSX_DEPLOYMENT_TARGET.

Regarding the Windows 2.7 stuff, I'm inclined to say 'if it ain't broke, don't fix it'. I don't have much interest in spending time improving the Python 2.7 support these days. But I won't stop somebody if there's a clean PR that improves things.

**Comment by YannickJadoul** [comment]
@henryiii I found the origin of the warnings about 10.3!

numpy sets it during compilation; see here: https://github.com/numpy/numpy/blob/0f6a3aaa34fe72586f8c66ecc4744fc960d62ae2/numpy/distutils/fcompiler/gnu.py#L116-L143

And rather than doing `sysconfig.get_config_var('MACOSX_DEPLOYMENT_TARGET')` (which PyPy does provide, it seems numpy tries to look it up in the Makefile used to build Python and defaults to 10.3. So I don't really think cibuildwheel is to blame for this.

@mattip You might be interested in this discrepancy between CPython and PyPy?
Short summary: @henryiii's CI now builds numpy (I guess there are no PyPy wheels available on PyPI?), which results in warnings (`UserWarning: Env. variable MACOSX_DEPLOYMENT_TARGET set to 10.3`, and `ld: warning: OS version (10.3.0) too small, changing to 10.4.0`, see [here](https://github.com/scikit-hep/boost-histogram/runs/549332108?check_suite_focus=true). That is weird, because normally if not set, `MACOSX_DEPLOYMENT_TARGET` is taken from the Python build (which should be 10.7 in PyPy's case, right?). The reason is because numpy's distutils for Fortran seems to use `sysconfig.get_makefile_filename` and `sysconfig.parse_makefile` (see above).

**Comment by YannickJadoul** [comment]
@henryiii I've created a PR testing this modern C++/recent MSVC for Python 2.7 workaround. See #333 for more details (and hopefully soon some updates to the docs).
