### ISSUE TITLE
Drop/Lock support for python 2.7

### ISSUE THREAD

**Issue by ShadowJonathan** [joerick/cibuildwheel#356]
While developing something for #340, I encountered this deprecation warning;

`pip 21.0 will drop support for Python 2.7 in January 2021.`

Python 2.7 support has been dropped begin 2020, would it be time to remove all support from `cibuildwheel` and make a note in the readme that version xyz was the last version with py2.7 support, or provide a "max pip version" with new versions and keep python 2.7 support?

**Comment by Czaki** [comment]
Many projects are using python2.7 and it is not a problem because pip version can be frezeed in  https://github.com/joerick/cibuildwheel/blob/master/cibuildwheel/resources/constraints-python27.txt

**Comment by YannickJadoul** [comment]
We've discussed this before in some random issues and PRs (that might not be too easy to find, so I'm not going to try). As long as the maintenance is OK, I vote to keep supporting Python 2.7, at least until crucial tools like pip start dropping it.

Also, PyPy 2.7 very likely won't be deprecated soon, and it would be nice to keep supporting it.

So currently, and until there's a pressing reason, I don't see why. But maybe at some point, we could make (C)Python 2.7 opt-in with an option, rather than opt-out, though? That could help push people towards not supporting 2.7 anymore?

**Comment by YannickJadoul** [comment]
Ah, there we go. At least 1 issue has a title related to this, and a reasonably discussion: #245

So I'm closing this issue for now. Feel free to reopen (or maybe reopen #245) if there's something to add to the discussion.

**Comment by ShadowJonathan** [comment]
Maybe after pip has dropped it, this issue can be reopened.

**Comment by YannickJadoul** [comment]
Yes, indeed, or maybe a bit before! I hadn't really realized that yet, but let's hope things become more clear over the next half year :-)
