### ISSUE TITLE
Build with cython and libopenmp

### ISSUE THREAD

**Issue by bluesheeptoken** [joerick/cibuildwheel#367]
Hello,

thank you for this project, really helpful and fast !

When trying this project, I had an issue on macos with openmp. This is a known issue on macos with openmp and cython.

You can find a full stack trace here: https://github.com/bluesheeptoken/CPT/issues/68, with a step by step resolution (maybe to update docker images and change the way wheels are built ?)

**Comment by Czaki** [comment]
Cibuildwheel use docker only for linux build. MacOS and Windows are build on machine provided by CI. cibuildwheel install only python on them. 

Installing any library from brew limits wheel to at least this system version. Otherwise it is possible to build binaries against older system version. Currently, if there is no brew libraries or compiler used wheel should work on any macos from version 10.9

Are you sure that libomp is enough to use openMP? I think that also usage of gcc/g++ compiler is mandatory. but if you confirm I will check again.

**Comment by bluesheeptoken** [comment]
Thanks for the explanation on how CIBuildwheel works, it is definitely helpful on linux part.

The problem with the machines provided by CI are we cannot use the included gcc/g++ with openmp (which leads to the issue I linked).

And you are right about gcc/g++

Closing the issue since the problem cannot / should not be solved in this project

**Comment by Czaki** [comment]
@bluesheeptoken 
In one project I build two wheels. One without openmp with minimal system version 10.9 and second with openmp build using gcc and libomp from brew witch minimal version 10.14  (because I  build on azure pipelines). You can also try travis ci. They have old one macos images so if brew will work then you can lower minimal system version.

**Comment by bluesheeptoken** [comment]
Which project of yours ? I would be glad to have a look at it

**Comment by Czaki** [comment]
https://github.com/czaki/imagecodecs
but I do refactor with subrepostiores https://github.com/czaki/imagecodecs_build (currently same problem because patch is skipped)
