### ISSUE TITLE
Would it be possible to deploy to pypi automatically from travis? 

### ISSUE THREAD

**Issue by zfrenchee** [joerick/cibuildwheel#4]
Check out [these travis docs](https://docs.travis-ci.com/user/deployment/pypi/#Uploading-different-distributions). I'm probably wrong, but would it be possible to upload these wheels directly, in the same step?

**Comment by joerick** [comment]
Yes that's possible, just make sure that you get your deploy rules set up right so you're not always trying to overwrite each version! I think PyPI won't overwrite existing wheels for each release.

**Comment by zfrenchee** [comment]
I've [added some deploy commands to my travis file](https://github.com/fraenkel-lab/pcst_fast/commit/19c82caa4f7ed4e1acc3af6103f030af23707a60), and my [build succeeds](https://travis-ci.org/fraenkel-lab/pcst_fast/jobs/222376069#L1116), but it [doesn't look like the wheels are being uploaded to pypi](https://pypi.python.org/pypi?:action=display&name=pcst_fast&version=1.0.2). What do you think?

**Comment by zfrenchee** [comment]
In [the macOS build](https://travis-ci.org/fraenkel-lab/pcst_fast/jobs/222376070#L671), something different happened, which made me think it might be the version number. I've upped the version number and I'm trying again.

**Comment by zfrenchee** [comment]
After updating the version number to `1.0.3` it doesn't seem like anything was uploaded to pypi. Would you mind working with me on this to establish definitive instructions for future users?

**Comment by joerick** [comment]
Hey! I think you might need the `skip_cleanup` option on your deploy. 

I've not added this to the docs because in the past I've found it really hard to get this kind of auto-deploy mechanism to work satisfactorily - for example, normally you'd set it to only deploy on a tag but say the build fails, then you've got to tag/release a whole new version just to fix the build. 

Also, you have to upload the sdist separately, but the wheel uploads will lag so some users will get sdist just because the wheel is still building. 

Sorry to be negative! I'm sure there's a good way to do it but I'm not ready to recommend anything yet! So for now my recommended method is a temporary storage location and a manual deploy. 

Do let me know if this works well for you though, it might become a case study for others to use. 👍

**Comment by zfrenchee** [comment]
Thanks as always for getting back to me @joerick. Apologies for being such a noob, but I have a few questions about this: 

1. You say in the "Manual Deploy" instructions: 

> `# Go and download your wheel files from wherever you put them.`

but I'm not sure in my current config where I'm even putting my wheels. My mental model for travis is that it's spinning up a VM, doing all these tasks, then throwing away all the data and reporting back whether it succeeded. It's putting all the wheels in `wheelhouse/` but I'm not sure how to access that directory, and I'm assuming it's removed once the travis job completes. Is that mental model incorrect? 

2. [Wheelhouse uploader](https://github.com/ogrisel/wheelhouse-uploader), which you recommend as the semi-automatic method, seems to mainly be built to upload wheels to clouds like s3, and then perhaps download them later to be uploaded to pypi. But it seems like s3 buckets are required to make it work. Am I reading that wrong -- Is there a way to use `wheelhouse uploader` to upload wheels from the travis VM?

**Comment by zfrenchee** [comment]
@joerick I'm also getting this other issue with wheelhouse uploader: https://github.com/ogrisel/wheelhouse-uploader/issues/21
