### ISSUE TITLE
Teamcity support

### ISSUE THREAD

**Issue by bioinfornatics** [joerick/cibuildwheel#44]
Dear,

Tanks for your awesome tools.
I would like to know if it is possible to add [teamcity](https://www.jetbrains.com/teamcity/) support  on your tools ?

Anyway thanks again for your great tools.

Best regards

**Comment by joerick** [comment]
It should be possible, for sure. Which platform are you running Teamcity on?

**Comment by bioinfornatics** [comment]
Currently we use a linux platform and we plan to add a Windows 64bit platform

Thanks a lot

Have a good day ;-)

**Comment by joerick** [comment]
So for the Linux platform you'll need Docker installed and running on the machine that runs the test. All the builds happen inside a container so there are no other special requirements.

For Windows, you'll need lots of versions of Python installed at specific paths on the build machine. See https://github.com/joerick/cibuildwheel/blob/master/cibuildwheel/windows.py#L33 for the exact paths.

cibuildwheel also won't automatically detect the environment that it's running on, so you'll have to specify that on the command line too. so instead of `cibuildwheel --output-dir wheelhouse .`, it's `cibuildwheel --platform linux --output-dir wheelhouse .` or `cibuildwheel --platform windows --output-dir wheelhouse .`.
