### ISSUE TITLE
pip: command not found

### ISSUE THREAD

**Issue by zfrenchee** [joerick/cibuildwheel#48]
Hi, 

I just pushed the first commit in a long time to my project, and cibw ran into a couple issues. The first was, on osx: 

```
$ pip install cibuildwheel==0.6.0
/Users/travis/.travis/job_stages: line 57: pip: command not found
```

This might be related to this issue: https://github.com/travis-ci/travis-ci/issues/8829 and perhaps fixed with this comment: https://github.com/travis-ci/travis-ci/issues/8829#issuecomment-348322979

**Comment by YannickJadoul** [comment]
Well, since this happens when you're installing `cibuildwheel`, it's indeed more of a problem with the Travis environment than with `cibuildwheel`.

That being said, I recently also had to fix my builds, and ended up with `python -m pip` or `python3 -m pip` (but according to that issue you mention, `pip2` or `pip3` should also do the job?)

**Comment by zfrenchee** [comment]
@YannickJadoul Since cibw is so dependent on travis, an issue with travis is an issue with cibw, imo. Also, at the very least, the docs / readme will need updating in accordance with this change. 

I believe changing to pip2/pip3 will fix this issue, but I don't want to change the command to pip3 for the python2.7 wheel builds -- that just seems wrong. What would be ideal is `{pip} install cibw` but I'm not certain that will work. @joerick what do you think?

**Comment by YannickJadoul** [comment]
Then main thing is that `cibuildwheel` can't really do anything about this, since the command you enter is the one that installs `cibuildwheel` (i.e., if `cibuildwheel` isn't installed, there's not a lot of code in this repository that can help to fix the problem, besides changing the example).

- `{pip}` is never going to work, because that's something `cibuildwheel` replaces once it's running, but we can't change that before it's installed.
- Running `pip3` for Python 2.7 builds is actually no problem either, since this will just be the outer Python interpreter. `cibuildwheel` will call the right version of Python interpreters while it's running.

**Comment by YannickJadoul** [comment]
I have just created a PR (#49) to fix the 'Minimal example' in the README, but I'm quite afraid that's about the only thing we can do about this issue

**Comment by zfrenchee** [comment]
@YannickJadoul changing `pip` to `pip3` did not work. 
```
The command "pip3 install cibuildwheel==0.6.0" exited with 127.
```
I'm now trying what you suggest, `python -m pip install...`

And no worries! That PR is what I was hoping for. Just want to make sure the provided example actually works.

**Comment by zfrenchee** [comment]
@YannickJadoul 
```
0.68s$ python -m pip install cibuildwheel==0.6.0
/usr/bin/python: No module named pip
The command "python -m pip install cibuildwheel==0.6.0" exited with 1.
```

**Comment by YannickJadoul** [comment]
Then I have no clue in what way Travis CI changed/messed up their build environment this time... :-|

Have a look at [this setup](
https://github.com/joerick/cibuildwheel/blob/master/.travis.yml), maybe? As far as I know, it is still [running and succeeding](https://travis-ci.org/joerick/cibuildwheel/builds/321866188)...

Seems that the `python` executable on OS X is the very old built-in one, now, and that you have to use `python2` in order to get the HomeBrew version?

Also, just out of curiosity: `The command "pip3 install cibuildwheel==0.6.0" exited with 127.`, what exactly went wrong there? What was the output before?

**Comment by YannickJadoul** [comment]
> Also, just out of curiosity: `The command "pip3 install cibuildwheel==0.6.0" exited with 127.`, what exactly went wrong there? What was the output before?

OK, so the 127 has to do with that weird Travis CI `rvm` error, and the actual problem is that `pip3` isn't installed (`brew install python3` would fix that, it seems in https://github.com/joerick/cibuildwheel/blob/master/.travis.yml, but ok...)

**Comment by joerick** [comment]
Hi @zfrenchee and @YannickJadoul, thanks for logging and debugging this! I took a look at your build @zfrenchee on pcst_fast, and it looks like the main difference to our builds is the Travis language specifier. It would probably be worth trying `language: python` or `language: generic` to see if `pip` exists and is correctly configured on those images.

**Comment by YannickJadoul** [comment]
> the main difference to our builds is the Travis language specifier.

For the record: [I'm running successfully](https://github.com/YannickJadoul/Parselmouth/blob/master/.travis.yml) with the `cpp` language specifier, so hopefully this shouldn't matter too much. But worth a try/check, indeed.

**Comment by zfrenchee** [comment]
- `language: python` worked for the linux build, but not the mac build (apparently [this is expected](https://github.com/travis-ci/travis-ci/issues/2312)). 
- [`language: generic` did not work for either](https://travis-ci.org/fraenkel-lab/pcst_fast/builds/323335989?utm_source=email&utm_medium=notification). 
- [`language: cpp` did not work for either](https://travis-ci.org/fraenkel-lab/pcst_fast/builds/323340708?utm_source=email&utm_medium=notification).

**Comment by joerick** [comment]
Ah, travis. not great that we have to clutter our travis YML with all these hacks. I agree we need to at least provide a working starting `.travis.yml` though. I'm going to have a play in a PR over on https://github.com/fraenkel-lab/pcst_fast.

**Comment by zfrenchee** [comment]
Using `pip2` solved it! Thanks @joerick !

**Comment by joerick** [comment]
So it seems one solution is to use `language: python` for Linux, but use `language: generic` for mac, and `pip2` instead of `pip`. I'll look at updating the example travis in the README
