### ISSUE TITLE
CIBW_BEFORE_BUILD is split/truncated on TravisCI

### ISSUE THREAD

**Issue by robbmcleod** [joerick/cibuildwheel#514]
In trying to build arm64/ppcle64 wheels on Travis, I am trying to set the environment variable `CIBW_BEFORE_BUILD: "pip install setuptools numpy"` in order to install my dependencies. If I look at the Travis job configuration, it seems to be correct (scroll down to see the configuration dictionary):

https://travis-ci.org/github/pydata/numexpr/jobs/752854159/config

However, in the actual jobs this gets split and somehow the environment variable is now just `pip` instead of `pip install setuptools numpy`, e.g.:

https://travis-ci.org/github/pydata/numexpr/jobs/752854159

My YAML file:

https://github.com/pydata/numexpr/blob/master/.travis.yml

Any thoughts?

**Comment by YannickJadoul** [comment]
First observation: that's already happening on Travis CI, though, so not inside `cibuildwheel`.

**Comment by YannickJadoul** [comment]
Did Travis CI change its syntax?

https://docs.travis-ci.com/user/environment-variables/#defining-public-variables-in-travisyml seems to be saying you should put `- CIBW_BEFORE_BUILD="pip install setuptools numpy"` ?

**Comment by robbmcleod** [comment]
@YannickJadoul yes you seem to be correct. When you use `=` instead of `: ` in setting an environment variable it escapes the quotations in the configuration:

https://travis-ci.org/github/pydata/numexpr/jobs/752859375/config

and then is seems to work. Although now it seems fairly involved in getting the wheels.

**Comment by YannickJadoul** [comment]
> Although now it seems fairly involved in getting the wheels.

@robbmcleod What do you mean? Normally, wheels ought to just be in the directory you specified (or `wheelhouse`. And your wheels seem to be there, as well, I see in the build. The import failing is because it's a wheel, and you never installed it?

Travis CI doesn't store artifacts (at least, when I was using it), so you have to "deploy" them somewhere, either to GitHub releases of one of the plenty of [other options Travis offers](https://docs.travis-ci.com/user/deployment/) (I have used Bintray for a while).

Can I close this issue? Feel free to keep asking questions (and I'll do my best to answer), but it seems these are not issues with `cibuildwheel` but just with Travis CI?

**Comment by YannickJadoul** [comment]
> The import failing is because it's a wheel, and you never installed it?

By the way, if you want to test, `cibuildwheel` offers `CIBW_TEST_COMMAND`: https://cibuildwheel.readthedocs.io/en/stable/options/#test-command

**Comment by henryiii** [comment]
Also, emulated ARM and other arch support is in master and will be in the next release; usable on GitHub Actions. ;)

**Comment by robbmcleod** [comment]
Oh, well @henryiii that would be much nicer than fighting with Travis. Thanks for everyone's help, closing.
