### ISSUE TITLE
set MACOSX_DEPLOYMENT_TARGET for all stages?

### ISSUE THREAD

**Issue by minrk** [joerick/cibuildwheel#563]
I recently adopted cibuildwheel (it is wonderful, thank you!), and made a broken release on older macs. The mistake I made was failing to set MACOSX_DEPLOYMENT_TARGET for the CIBW_BEFORE_ALL stage. I was surprised to see that CIBW has the feature to set MACOSX_DEPLOYMENT_TARGET, but doesn't do it for all stages.

#306 sets MACOSX_DEPLOYMENT_TARGET for python commands, but I was building a library dependency in CIBW_BEFORE_ALL.

My wheels are roughly:

- CIBW_BEFORE_ALL compiles and installs a library
- build my wheel that links the library
- repair (auditwheel/delocate/delvewheel) bundles the library in the wheel

So my question is: should I have built the library in a different stage, or does it make sense to set the default MACOSX_DEPLOYMENT_TARGET for all commands, not just the python environment?

Fixing it was easy enough (set MACOSX_DEPLOYMENT_TARGET in global env)

**Comment by joerick** [comment]
Ah, I see. Yes the BEFORE_ALL commands on macOS and Windows run outside of a cibuildwheel Python environment, so we haven't set our environment variables yet. 

Your workflow sounds sensible to me. (The only snag I can think of will be that once `universal2` is supported (#484), you'll have to build your shared lib as universal2, also. But I think delocate should be able to handle it)

I'm not sure that we've built-in the assumption that BEFORE_ALL is for _building_ dependencies exactly, but, it does seem pretty harmless to add `env.setdefault('MACOSX_DEPLOYMENT_TARGET', '10.9')` there. The other question we could consider, is 'should we run the macos BEFORE_ALL inside one of our Python environments, rather than in the system environment?' We do that on Linux, but that was only because the system Python on `manylinux `was 2.6 or something ancient.

But it's probably easier to do the simple thing - adding `env.setdefault('MACOSX_DEPLOYMENT_TARGET', '10.9')` before calling BEFORE_ALL.

**Comment by henryiii** [comment]
`env.setdefault('MACOSX_DEPLOYMENT_TARGET', '10.9')` would still provide strange behavior if someone set `CIBW_ENVIRONMENT: MACOSX_DEPLOYMENT_TARGET=10.14` (say, for C++17 support)? Seems like the correct thing would be to match Linux on Windows/macOS and make the environment affect all steps, since it already does that on Linux? We need to be careful not to override `MACOSX_DEPLOYMENT_TARGET` - most projects _should_ be setting it, really, for constancy and control, but many don't.

**Comment by vegardjervell** [comment]
Just in case anyone comes looking here (like me) and doesn't immediately know how to "set MACOS_DEPLOYMENT_TARGET in the global env", what you want is to add the step

```
- name: Set macOS deployment target
  run: echo "MACOSX_DEPLOYMENT_TARGET=$(sw_vers -productVersion | cut -d '.' -f 1-2)" >> $GITHUB_ENV
```
before your `cibuildwheel` step, where the command `sw_vers -productVersion | cut -d '.' -f 1-2` is used to detect the runners macOS version (if you're building for several versions, if not just specify it explicitly). To check that it was set correctly, you can use


```
- name: Check macOS deployment target
  run: echo "Deployment target version is ${{ env.MACOSX_DEPLOYMENT_TARGET }} / ${MACOSX_DEPLOYMENT_TARGET}"
```

where `${{ env.MACOSX_DEPLOYMENT_TARGET }}` and `${MACOSX_DEPLOYMENT_TARGET}` should be the same value.
