### ISSUE TITLE
docs: update table mentioning emulation & Apple ARM

### ISSUE THREAD

**Issue by henryiii** [joerick/cibuildwheel#575]
The table in the readme still says you have to have a third party build host for ARM - we should add something for emulation, especially places we test it (GHA). Also Univeral2/ARM64 should probably go there.

**Comment by henryiii** [comment]
@joerick Shouldn't this go in before release (at least the Universal/Arm part)? Would you like to tackle it, or should I?

**Comment by joerick** [comment]
Yes, good point. Planning to do a release tomorrow, if you get a chance today, that would be ace, otherwise, no worries , I can do it tomorrow before release. 

The other thing I realised is that we should shift over the GHA examples to use the new action syntax and declare proper support in this release, too.

**Comment by henryiii** [comment]
I think all the Scikit-HEP projects using cibuildwheel have updated to the action syntax (boost-histogram, iminuit, and the other two). After this next release, I'll be really trying to get Awkward moved over! (unless we have a baby first, in which case it will be severely delayed ;) ).

**Comment by henryiii** [comment]
Fantastic, looks good! So we have Universal support, Requires-Python, auto64/auto32, and final wheel printout incoming as new features. :)

**Comment by joerick** [comment]
Yep! a big release! just updated the changelog and pushed to PyPI.
