### ISSUE TITLE
Add cp*-linux* CIBW_BUILD Option

### ISSUE THREAD

**Issue by coreylammie** [joerick/cibuildwheel#584]
Currently, linux builds must be compiled using manylinux on CentOS. It would be helpful to add support to build cp*-linux* wheels. Many popular python packages, such as torch ([https://download.pytorch.org/whl/torch_stable.html](https://download.pytorch.org/whl/torch_stable.html)) have stopped distributing manylinux* wheels in recent versions, and instead release cp*-linux* wheels. This causes problems when trying to import some packages, as they are required to be compiled from source if a manylinux* wheel is not available, and a cp*-linux*wheel is.

**Comment by henryiii** [comment]
PyTorch is manylinux1 (even on 3.9): https://pypi.org/project/torch/#files

I believe "linux" basically means you promise nothing about compatibility and just built it yourself without following the manylinux limitations; and you are not allowed to upload it to pypy, since there's no knowing where it can be installed. If you just want to compile it yourself without any rules, you don't need cibuildwheel.

PS: The reason for this, in PyTorch's case, I believe, is because they are adding CUDA support, and couldn't manage to do it with manylinux1. But this is a guess.

Happy to be corrected if I'm wrong! :)

**Comment by henryiii** [comment]
Also, now that I think of it, I think auditwheel is actually the tool that puts the "many" in the name. So if you used `CIBW_REPAIR_WHEEL_COMMAND_LINUX: ""` in your config, you would probably get "linux" wheels, since that's what's directly produced (say if you build from source).

**Comment by YannickJadoul** [comment]
And using a custom Docker image then? Otherwise, there wouldn't be much point in not having on-`manylinux`-built wheels not be renamed to `manylinux`, most likely?

**Comment by henryiii** [comment]
You'd probably use this for something like that, yes. Facebook might be using "linux" so they can use CUDA in PyTorch but assume it is on your system and not bundle it in, which makes the wheel huge, perhaps?

**Comment by joerick** [comment]
As @henryiii mentioned, you can build `linux` wheels if you'd like by doing `CIBW_REPAIR_WHEEL_COMMAND_LINUX: ""`. But you probably don't want to do that, because the wheels might not work on other machines.
