### ISSUE TITLE
Get latest manylinux2014 image

### ISSUE THREAD

**Issue by musicEnfanthen** [joerick/cibuildwheel#603]
Hi there. Thanks for this helpful tool!

Is there a way to get the latest manylinux2014 image with cibuildwheel. Using CBW version 1.9 with the gh-actions-style approach described in the README, seems to pull an "older" image ([quay.io/pypa/manylinux2014_x86_64:2021-01-24-91ce2b8](https://quay.io/repository/pypa/manylinux2014_x86_64?tag=2021-01-24-91ce2b8&tab=tags))

Trying to pull the images in an GH action here: https://github.com/musicEnfanthen/verovio/runs/1930266433?check_suite_focus=true#step:6:36 which results in an error later on because SWIG is only included in more recent images.

Is this expected, or do I miss something in the settings ([https://github.com/musicEnfanthen/verovio/blob/swig-test/.github/workflows/python-ci-wheel.yml#L80-L93](https://github.com/musicEnfanthen/verovio/blob/swig-test/.github/workflows/python-ci-wheel.yml#L80-L93))?

Thanks in advance.

**Comment by mayeut** [comment]
`cibuildwheel` uses tagged images by default in order for builds to be reproducible. The ones used for `manylinux2014` with `cibuildwheel 1.9.0` are older than the ones you want, as you noticed, because those didn't exist at the time `cibuildwheel` was released.
As mentioned in the [docs](https://cibuildwheel.readthedocs.io/en/stable/options/#manylinux-image), the `CIBW_MANYLINUX_X86_64_IMAGE ` and `CIBW_MANYLINUX_I686_IMAGE` environment variables - the ones you're already using to specify `manylinux2014 ` - can be set to any valid Docker image name.

You can use `quay.io/pypa/manylinux2014_x86_64:2021-02-17-8d1372a` and `quay.io/pypa/manylinux2014_i686:2021-02-17-8d1372a` in order to get images including swig.

**Comment by musicEnfanthen** [comment]
Thanks for the quick response and clarification. Totally makes sense in the light of reproducibilty. Works perfectly with the specified image name: https://github.com/musicEnfanthen/verovio/runs/1934208139?check_suite_focus=true.

Just as a thought for the [docs](https://cibuildwheel.readthedocs.io/en/stable/options/#manylinux-image): Maybe the statement: 

> Alternatively, set these options to any other valid Docker image name.

could benefit from an example or a hint where to find those image names. And/or a hint in the README here, to which image a certain version of cibuildwheel is pinned?

**Comment by YannickJadoul** [comment]
> > Alternatively, set these options to any other valid Docker image name.
> 
> could benefit from an example or a hint where to find those image names.

Well, that's basically just anything that you can use for `docker run ...`, so that's why it's a bit vague.

It is shown in the examples below that section, btw:

```
# build using the latest manylinux2010 release, instead of the cibuildwheel
# pinned version
CIBW_MANYLINUX_X86_64_IMAGE: quay.io/pypa/manylinux2010_x86_64:latest
CIBW_MANYLINUX_I686_IMAGE: quay.io/pypa/manylinux2010_i686:latest
```

**Comment by musicEnfanthen** [comment]
Ah, I see, it's all there. Sorry, my bad, did not apply the example to the use case here :( .

Thanks again for your quick help! I close the issue.

**Comment by YannickJadoul** [comment]
> Ah, I see, it's all there. Sorry, my bad, did not apply the example to the use case here :( .

Maybe it's not entirely clear, then? (Things that are obvious to the maintainers might not be obvious to the actual users.)
