### ISSUE TITLE
ARMv7l wheels

### ISSUE THREAD

**Issue by ColdHeat** [joerick/cibuildwheel#642]
Sorry if this is obvious but is it possible to use cibuildwheel to create an armv7l wheel for manylinux2014? 
I've been trying it for awhile and it doesn't seem like it's doable even with the qemu emulated builds?

**Comment by joerick** [comment]
hey! so, the Manylinux project doesn't publish armv7 Docker images, that would be your first problem. I guess they might not be all that keen to add one at this point, armv7 is a 32bit arch and they seem to be phasing out the 32 bit archs due to spotty compiler support. But you could go ask :)

If there was a armv7 Docker image, then cibuildwheel would also need to add support for the new architecture. Not a big job, assuming it all goes smoothly! I don't think there would be a problem emulating armv7 through qemu. 

I'm curious - what's your use-case for compiling armv7?

**Comment by ColdHeat** [comment]
Yeah I figured that was the problem. Perhaps there's an alternative Docker image that could be used?

My use case currently is getting Raspberry Pi wheels for https://github.com/ColdHeat/pybluemonday. [Piwheels](https://www.piwheels.org/) isn't building it properly b/c it uses golang and I'm trying to see if this is something I can automate myself.

**Comment by joerick** [comment]
Ah yes, I had forgotten about Piwheels! Thanks for the reminder. That's probably a better way to go for this sort of thing, I think. I see you're making some progress in https://github.com/piwheels/packages/issues/197 :)

**Comment by joerick** [comment]
> Perhaps there's an alternative Docker image that could be used?

Yes, perhaps. If you were able to find/create one, you could try plugging it into one of the `CIBW_MANYLINUX_*_IMAGE` options (perhaps `CIBW_MANYLINUX_I686_IMAGE` as that's also 32-bit). But we're getting pretty hacky at this point :)

**Comment by joerick** [comment]
Another idea for you, if you're interested - I just came across https://github.com/messense/manylinux2014-cross-arm, which could perhaps be used to cross-compile, here's an example usage: https://github.com/messense/fasttext-wheel/commit/b6bd26dabf676a24a0aafb1f37a349273b435468. However, I don't know how this would interact with the go binding...
