### ISSUE TITLE
Windows wheels are not built for python 3.7

### ISSUE THREAD

**Issue by jlaine** [joerick/cibuildwheel#75]
On Linux wheels are correctly built for all supported python versions. Windows however stops at python 3.6.

Looking at windows.py there seem to be no references to python 3.7

**Comment by YannickJadoul** [comment]
As far as I can see, AppVeyor currently does not include Python 3.7 yet (cfr. https://github.com/appveyor/ci/issues/2475), which is why we have not enabled the 3.7 build.

So you'll either have to install Python 3.7 yourself (cfr. failing build #76), or we can wait until somewhere next week (which seems fine enough to me?)

**Comment by jlaine** [comment]
Ah I see. I wasn't sure what to make of the CI failure, as the error was a "file already exists" error.

**Comment by YannickJadoul** [comment]
Yeah, I noticed the weird error as well, but since I'm seeing something with `27` in the file name, I'm guessing that the default AppVeyor Python is run (because the directory prepended to the `PATH`, i.e. `C:\Python37\` does not exist).
