### ISSUE TITLE
Refactoring the Linux build script

### ISSUE THREAD

**Issue by joerick** [joerick/cibuildwheel#99]
Currently the linux build works by piping a bash script into /bin/bash inside the docker container.

A couple good ideas have come out of the discussion in #97, so I wanted to keep them in an open issue!

1. @altendky: maybe a good way would be a Python script with a CLI (probably small enough to comfortably do with stdlib and 2/3 compatibility) and we pass in the info via the command. No config file to write and copy, no template to fill out. Just copy the exact Python script over to the container and then docker run it with proper arguments.

2. @altendky: Or, maybe we just replace the string/file with python code calling docker run for each command?

**Comment by altendky** [comment]
You could use `check_output()` as the general rule instead and could then read out variables and directory listings.  Just make sure of things like having `ls` output a file per line rather than splitting on spaces (hmm, can a file have a newline?).

https://docs.docker.com/engine/reference/run/#env-environment-variables

For setting env var you can (1) `['-e', 'deep=purple', 'do', 'something']` or (2) have the function take an additional dict for extra env vars or (3) `**kwargs` for env vars.  I think (2) uses Python syntax and is explicit and flexible so I'd tend towards that.

**Comment by joerick** [comment]
The piped bash script was removed in #386 - replaced with a system similar to (2) above, but using a shell process and open pipes instead of `docker exec` for performance reasons. So this is fixed :)
